{% set name = "pwkit" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pwkit-{{ version }}.tar.gz
  sha256: 9cbae4bdb099dd0473482987995e51d2b605946afcee5281582efb97c8294903

build:
  entry_points:
    - astrotool = pwkit.cli.astrotool:commandline
    - casatask = pwkit.environments.casa.tasks:commandline
    - imtool = pwkit.cli.imtool:commandline
    - latexdriver = pwkit.cli.latexdriver:commandline
    - pkcasascript = pwkit.environments.casa.scripting:commandline
    - pkenvtool = pwkit.environments:commandline
    - wrapout = pwkit.cli.wrapout:commandline
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.6

test:
  requires:
    - numpy
    - pip
    - python {{ python_min }}
  imports:
    - pwkit
  commands:
    - pip check
    - astrotool --help
    - casatask --help
    - imtool --help
    - latexdriver --help
    - pkcasascript --help
    - pkenvtool --help
    - wrapout echo hello world

about:
  home: https://github.com/pkgw/pwkit/
  summary: Miscellaneous scientific and astronomical tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
