{% set name = "pwkit" %}
{% set version = "0.8.18" %}
{% set sha256 = "4515af858756616cc759e48e520cb71d3961921ce16783fec740d3dfab4af78c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=files.txt
  entry_points:
    - astrotool = pwkit.cli.astrotool:commandline
    - casatask = pwkit.environments.casa.tasks:commandline
    - imtool = pwkit.cli.imtool:commandline
    - pkcasascript = pwkit.environments.casa.scripting:commandline
    - pkenvtool = pwkit.environments:commandline
    - wrapout = pwkit.cli.wrapout:commandline

requirements:
  build:
    - python
    - setuptools

  run:
    - pathlib
    - python
    - six

test:
  requires:
    - numpy
  imports:
    - pwkit
  commands:
    - astrotool flux2lum 1e-15 10
    - imtool help
    - pkenvtool --help
    - wrapout echo hello

about:
  home: https://github.com/pkgw/pwkit/
  license: MIT
  license_family: MIT
  summary: 'Miscellaneous scientific and astronomical tools.'
  description: |
    A grab-bag of helpful tools for doing science in Python.
  doc_url: https://pwkit.readthedocs.io/
  dev_url: https://github.com/pkgw/pwkit

extra:
  recipe-maintainers:
    - pkgw
