{% set name = "pwkit" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pwkit-{{ version }}.tar.gz
  sha256: e2adc5064c686003a5a019214c33f514b6e5f9220b9ff683cdb32a85e8cd0b56

build:
  entry_points:
    - astrotool = pwkit.cli.astrotool:commandline
    - casatask = pwkit.environments.casa.tasks:commandline
    - imtool = pwkit.cli.imtool:commandline
    - latexdriver = pwkit.cli.latexdriver:commandline
    - pkcasascript = pwkit.environments.casa.scripting:commandline
    - pkenvtool = pwkit.environments:commandline
    - wrapout = pwkit.cli.wrapout:commandline
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - numpy >=1.6

test:
  requires:
    - numpy
  imports:
    - pwkit
  commands:
    - pip check
    - astrotool --help
    - casatask --help
    - imtool --help
    - latexdriver --help
    - pkcasascript --help
    - pkenvtool --help
    - wrapout echo hello world
  requires:
    - pip

about:
  home: https://github.com/pkgw/pwkit/
  summary: Miscellaneous scientific and astronomical tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
