{% set name = "pwkit" %}
{% set version = "1.0.0" %}
{% set sha256 = "095319d0f8ab600d3be7d85ba95e24623a91b597da861e7977fc1ed5c3295644" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - astrotool = pwkit.cli.astrotool:commandline
    - casatask = pwkit.environments.casa.tasks:commandline
    - imtool = pwkit.cli.imtool:commandline
    - pkcasascript = pwkit.environments.casa.scripting:commandline
    - pkenvtool = pwkit.environments:commandline
    - wrapout = pwkit.cli.wrapout:commandline

requirements:
  build:
    - pip
    - python
    - setuptools

  run:
    - pathlib
    - python
    - six

test:
  requires:
    - numpy
  imports:
    - pwkit
  commands:
    - astrotool flux2lum 1e-15 10
    - imtool help
    - pkenvtool --help
    - wrapout echo hello

about:
  home: https://github.com/pkgw/pwkit/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Miscellaneous scientific and astronomical tools.'
  description: |
    A grab-bag of helpful tools for doing science in Python.
  doc_url: https://pwkit.readthedocs.io/
  dev_url: https://github.com/pkgw/pwkit

extra:
  recipe-maintainers:
    - pkgw
