travis:
  secure:
    BINSTAR_TOKEN: 2uTG6DKsYRrgQeBH7Re9ijSmc7+wiJgMcgQT/yqVG58UcR/GspJgKz781TqGZGj7kKUDs3n7W4hc+4ayA7D7sS71dIFzNvuWHprcOnE5D8s+ZjKxkrZ821k6jGrLaeethsW/K6SjMQ0+btnlsTO4WeU05FCS8A7S160syVpEqloVNaF4rZohZwaACezf9C7huSq/UPYW9GnoUEWYhiSThm62naW8K2lPcB3zbJkQIsZDN5yDCmvRT/IMSACqPR6zNsf08S2+vgtOODoTTJrKb6JAylIquXfY98Crz1fpFu3dg/wBo1Q+AppVfokkkWPW0jkd5IcvqBMeEyI9vvqy1R5GxnYUuPux+n+kxPVBo2CaqKGifrOiMULDFwl4beHxBSgLuKZx8GbbDiPP6ocU3CEooRTM3FnV/fK2DIcVdFoZsEln+3Yr0aHEAwTcxIhbm8S2R7x1ehqBZnDcinsZaOLPgBemRdUJgB6MQvRSQeXHSmyyShAr6B2cy4PzgnwguJcWF4z/VNqehG4yePWm4Cx1iEdQKvWE3RRfytqrd/MyQTCw9+BU9n67pFrWvSDmMZpLxtP/cFXvjlpT0mkp6c+XKiYo3W9Lb3PMp5ebUO6ZMjOLOz8dCzoMQQ2n5e+jB0M3KzSJTF0oUQ+Jmhch3brAhH1Hn+3FZuazwB6/4v8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
