travis:
  secure:
    BINSTAR_TOKEN: clnINMml//RYH3s2+wOtuW57NOeKGSdc+nqlr8dQp6zMNmKVkq/iuYIRlzH/SSqbsEgCirD+yGqYjgmpNyORxOEx6U5m6siVTm2Q78Pwdg2mlvqTMzQlDaTWQ0jUBbayuWiJ1c2ii1mRN3zrPVVkdpbWwID4rjtfNWZCp0OP/KNS1cJHge5LbMKDCXVzc1+yOmKocBUqsrkffIB8VU473SeoywPsZky3UAjG1Qm0YfgOhTFuC9Wxl3vc4SkQ3zp8uFSu7T6/tPNGK4xBp1ciDBq7e/Cvh4ybfkoWZbMYHkJtJHqy+hbKRBdYTIRimRxz7X5C2g7zRtIre+17cEcc1MkggLViQddGsWn5Lh5txpatRfmeEoWzeIr1Kx1hKmvLNvDf5feEINBqsZJ7MTiRewx6GFblYzqo19ovByCNcVyOl7EexoScb6lqjTLnDumlpZOZkNyob49y1iOu5NL1eMjad9ug+Ovf+C1OiUTTcciL920m9i30YMuuT+NWQi5U9tpe1sD/KFnm4bxTOQokLscTZ35+YemTlY4xZdE2IzzC/Zg75r3BGa6WKFsFl6NKpdT7iCsI7niUZiydot18qEZFg7LONQLKz7lw38gm0bz7tlBGH41pQwJiJwU5LqUHGUvBwEuabz+NjIhJQ4EUZIglcVagaPsCvk5dccKG1Ak=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
